apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapRef }}
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
