{{- if .Values.preview.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.label }}
  labels:
    app: {{ .Values.label }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.label }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.label }}
    spec:
      serviceAccountName: '{{ .Values.global.namespace }}-{{ .Values.label }}'
      containers:
        - name: {{ .Values.label }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: {{ .Values.command }}
          args: {{ .Values.args }}
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: {{ .Values.configMapRef }}
          - secretRef:
              name: {{ .Values.secretRef }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelay }}
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 8080
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelay }}
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: 8080
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
{{- end }}
