apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretRef }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.label }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: "{{ .Values.global.namespace }}-secretstore"
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretRef }}
  data:
  {{- with .Values.sharedSecrets }}
    {{- range . }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ $.Values.secrets.namespace }}-shared-secrets-manager
        property: {{ .key }}
    {{- end }}
  {{- end }}
  {{- if and .Values.appSecrets (ne (index .Values.appSecrets 0).key "NO_SECRETS") }}
    {{- range .Values.appSecrets }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ $.Values.secrets.namespace }}-{{ $.Values.label }}-secrets-manager
        property: {{ .key }}
    {{- end }}
  {{- end }}
