{{- if .Values.preview.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ .Values.global.namespace }}-{{ .Values.label }}-preview-hpa'
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.label }}
  minReplicas: {{ .Values.minReplicas | default 3 }}
  maxReplicas: {{ .Values.maxReplicas | default 3 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
{{- end }}