apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.label }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.label }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  type: NodePort

{{- if not .Values.preview.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: "{{ .Values.label }}-progressive-deployment"
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.label }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  type: NodePort
{{- end }}