{{- if not .Values.preview.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.label }}
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Values.label }}
  pollingInterval:  30
  cooldownPeriod:   300
  minReplicaCount:  {{ .Values.minReplicas }}
  maxReplicaCount:  {{ .Values.maxReplicas }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 900
          policies:
          - type: Percent
            value: 10
            periodSeconds: 60
        scaleUp:
          policies:
          - type: Percent
            value: 50
            periodSeconds: 60
  triggers:
  - type: aws-cloudwatch
    metricType: Value
    metadata:
      namespace: AWS/ApplicationELB
      dimensionName: TargetGroup
      dimensionValue: {{ .Values.scaling.targetGroupName }}
      metricName: {{ .Values.scaling.metricName }}
      targetMetricValue: "{{ .Values.scaling.targetMetricValue }}"
      minMetricValue: "{{ .Values.scaling.minMetricValue }}"
      activationTargetMetricValue: "{{ .Values.scaling.activationTargetMetricValue }}"
      awsRegion: "us-east-1"
      identityOwner: operator
      metricCollectionTime: "180"
      metricStat: {{ .Values.scaling.metricStat }}
      metricStatPeriod: "60"
{{- end }}